server:
  port: 9002

eureka:
  instance:
    hostname: ek2.com
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: http://ek1.com:9001/eureka/

spring:
  application:
    name: EurekaServer